name: Python CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Встановлюємо стабільну версію pyspellchecker
        pip install pyspellchecker==2.1.0
        pip install -r requirements.txt
        pip install pytest
        
    - name: Run tests
      run: |
        pytest tests/ -v