name: Python CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11  # Використовуємо 3.11 для numpy 2.x
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Спочатку встановлюємо numpy сумісну версію
        pip install numpy==2.2.4
        # Потім інші залежності
        pip install -r requirements.txt
        pip install pytest
        
    - name: Run tests
      run: |
        pytest tests/ -v